name: minimals
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  flutter_staggered_grid_view: ^0.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  numberpicker: ^2.1.1
  lottie: ^1.2.1
  vibration: ^1.7.4-nullsafety.0
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.0.0
  glassmorphism_ui: ^0.2.0
  syncfusion_flutter_sliders: ^19.4.40
  syncfusion_flutter_core: ^19.4.40
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.0.8
  shared_preferences: ^2.0.8
  http: ^0.13.3
  shimmer: ^2.0.0
  timeline_tile: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/images/icons/
    - asset/images/home/
    - asset/images/mens/
    - asset/images/womens/
    - asset/images/accessories/
    - asset/images/randomiser/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: adam
      fonts:
        - asset: asset/fonts/adam/Adam-Bold.ttf
#        - asset: asset/fonts/adam/Adam-Light.ttf
#          weight: 200
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

    - family: play
      fonts:
        - asset: asset/fonts/Playfair_Display/static/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: asset/fonts/Playfair_Display/static/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: asset/fonts/Playfair_Display/static/PlayfairDisplay-ExtraBold.ttf
          weight: 900

    - family: gotham
      fonts:
        - asset: asset/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: asset/fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: asset/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700
        - asset: asset/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 900
    - family: basker
      fonts:
        - asset: asset/fonts/Baskerville Bold.otf
    - family: popins-r
      fonts:
        - asset: asset/fonts/Poppins-Regular.otf
    - family: popins-s
      fonts:
        - asset: asset/fonts/Poppins-SemiBold.otf
    - family: popins-b
      fonts:
        - asset: asset/fonts/Poppins-Bold.otf

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
